// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBoleta.Infrastructure;

#nullable disable

namespace SmartBoleta.Infrastructure.Migrations
{
    [DbContext(typeof(SmartBoletaDbContext))]
    [Migration("20251110022047_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartBoleta.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoPor")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_por");

                    b.Property<string>("ColorPrimario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("color_primario");

                    b.Property<string>("CreatedPor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_por");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("favicon_url");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo_url");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("Ruc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ruc");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
